name: Bug report
description: File a bug report
labels: 'bug'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Screenshots are welcome!
    validations:
      required: true
  - type: textarea
    id: how-to-reproduce
    attributes:
      label: What are the steps to reproduce the bug?
    validations:
      required: false
  - type: input
    id: browser
    attributes:
      label: What browser are you running?
      placeholder: Mozilla Firefox
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Which version?
    validations:
      required: true
  - type: dropdown
    id: device
    attributes:
      label: On which device?
      options:
        - Phone
        - Tablet
        - Desktop
      default: 0
    validations:
      required: true
  - type: textarea
    id: extensions
    attributes:
      label: Do you use any extensions, such as uBlock Origin or Dark Reader?
      description: Please provide a list.
    validations:
      required: false
