name: Improvement proposal
description: File an improvement proposal (new selectors or properties, performance tricks, one-liners...)
labels: 'improvement'
body:
  - type: textarea
    id: improvement
    attributes:
      label: What do you think can improve this project?
      placeholder: Mozilla just added support for CSS nesting, it might make the code better and more maintainable...
    validations:
      required: true
  - type: textarea
    id: sources
    attributes:
      label: Provide sources (such as MDN) that describe the improvement.
